name: Run tests

on:
  pull_request:
    paths-ignore:
      - 'projects/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check formatting of source files
        run: bun check

      - name: Validate CDDL files
        run: bun test
